### ISSUE TITLE
Is it posible to make it work with [toc]

### ISSUE THREAD

**Issue by BenjaminHoegh** [KEINOS/parsedown-extension_table-of-contents#2]
Is it posible to make it work with [toc] ???

**Comment by KEINOS** [comment]
@BenjaminHoegh 

Sadly, so far at this latest commit 4e9af97, NO. 😭 

Though, I agree and like your idea. It would be nice if we can have a `[toc]` markdown tag which works like below:

- Markdown
    ```markdown
    [toc]
    
    ---
    
    # Head1
    Sample text of head 1.
    ## Head1-1
    Sample text of head 1-1.
    ```
- Result
    ```html
    <ul>
    <li><a href="#Head1">Head1</a>
    <ul>
    <li><a href="#Head1-1">Head1-1</a></li>
    </ul></li>
    </ul>
    <hr>
    <h1 id="Head1" name="Head1">Head1</h1>
    <p>Sample text of head 1.</p>
    <h2 id="Head1-1" name="Head1-1">Head1-1</h2>
    <p>Sample text of head 1-1.</p>
    ```

It might be a feasible idea if we can replace the `[toc]` tag to the value which [`contentsList()` method](https://github.com/KEINOS/parsedown-extension_table-of-contents/blob/4e9af97776ad4424d00c9171eca091ece5a053b1/Extension.php#L28-L41) was holding at some point. Maybe by overriding the `text()` method?

**Comment by KEINOS** [comment]
A simple workaround with the [current version](https://github.com/KEINOS/parsedown-extension_table-of-contents/blob/4e9af97776ad4424d00c9171eca091ece5a053b1/Extension.php) would be:

```php
<?php
include_once('Pasedown.php');
include_once('Extension.php');

$textMarkdown =<<<EOL
[toc]

---
# Head1
Sample text of head 1.
## Head1-1
Sample text of head 1-1.
# Head2
Sample text of head 2.
## Head2-1
Sample text of head2-1.
EOL;

$Parsedown = new Extension();
$body = $Parsedown->text($textMarkdown);
$ToC  = $Parsedown->contentsList();

// Replace `[toc]` to generated tabe of contents
$body = str_replace('[toc]', $ToC, $body);

echo $body . PHP_EOL;
```

- [Online Demo](https://paiza.io/projects/chSkYXV9ydSVrKhsnAuLBA) @ paiza.IO

**Comment by KEINOS** [comment]
## [toc] now available!

> @BenjaminHoegh
> Is it posible to make it work with [toc] ???

As of f027f1fbb11f3a46668387234ef63893ad7891ee, now it works with `[toc]` tag! Thanks for waiting.

- The Markdown file:
```markdown
[toc]

---

# One
Something about One

## Two
Something about Two

# One2
Something about One2
```

The PHP file. (`composer require keinos/parsedown-toc` before use)

- NOTE: the main class' name's been changed from `Extension()` to `ParsedownToC()` since v1.0.1

```php
require_once __DIR__ . '/vendor/autoload.php';

$Parsedown = new \ParsedownToC();
$text_markdown = file_get_contents('SAMPLE.md');
$html = $Parsedown->text($text_markdown);

echo $html . PHP_EOL;
```

The result

```shellsession
$ php main.php
<div id="toc"><ul>
<li><a href="#One">One</a><ul>
<li><a href="#Two">Two</a></li>
</ul>
</li>
<li><a href="#One2">One2</a></li>
</ul></div>
<hr />
<h1 id="One" name="One">One</h1>
<p>Something about One</p>
<h2 id="Two" name="Two">Two</h2>
<p>Something about Two</p>
<h1 id="One2" name="One2">One2</h1>
<p>Something about One2</p>
```

Closing the issue. But feel free to re-open the issue if it's not working!
